{
    "0": "Moon Sign \"Moonlight Ray\"",
    "2": "Night Sign \"Night Bird\"",
    "4": "Night Sign \"Night Bird\"",
    "6": "Darkness Sign \"Demarcation\"",
    "8": "Darkness Sign \"Demarcation\"",
    "9": "Darkness Sign \"Demarcation\"",
    "10": "Large Ring \"Umbrella Halo\"",
    "12": "Large Ring \"Hello Forgotten World\"",
    "14": "Umbrella Sign \"Parasol Star Symphony\"",
    "16": "Umbrella Sign \"Parasol Star Memories\"",
    "18": "Rain Sign \"A Rainy Night's Ghost Story\"",
    "20": "Umbrella \"Super Water-Repelling Bone-Dry Monster\"",
    "22": "Monster Sign \"A Forgotten Umbrella's Night Train\"",
    "24": "Monster Train \"Spare Umbrella Express Night Carnival\"",
    "26": "Iron Fist \"An Unarguable Youkai Punch\"",
    "28": "Divine Fist \"Hell Thrust from Above the Clouds\"",
    "29": "Divine Fist \"Hell Thrust from the Heavenly Seas\"",
    "30": "Fist Sign \"Heavenly Net Sandbag\"",
    "32": "Barrage \"Cloud World Kraken Strike\"",
    "33": "Barrage \"King Kraken Strike\"",
    "34": "Hand Strike \"Fist Smash\"",
    "36": "Annihilation \"Consecutive Hooks Throughout Heaven & Earth\"",
    "38": "Thunderous Yell \"A Scolding from a Traditional Old Man\"",
    "40": "Rage \"Calamity Scolding Scorch\"",
    "41": "Rage \"First & Last of Its Kind Scolding Scorch\"",
    "42": "Capsize \"Dragging Anchor\"",
    "44": "Capsize \"Foundering Anchor\"",
    "45": "Capsize \"Sinking Anchor\"",
    "46": "Drowning Sign \"Deep Vortex\"",
    "48": "Drowning Sign \"Sinkable Vortex\"",
    "50": "Harbor Sign \"Phantom Ship Harbor\"",
    "52": "Harbor Sign \"Phantom Ship's Port\"",
    "53": "Harbor Sign \"Eternally Anchored Phantom Ship\"",
    "54": "Phantom \"Sinker Ghost\"",
    "55": "Phantom \"Dipper Creeping Close\"",
    "56": "Phantom \"Dipper Creeping Close\"",
    "57": "Jeweled Pagoda \"Greatest Treasure\"",
    "59": "Jeweled Pagoda \"Greatest Treasure\"",
    "60": "Jeweled Pagoda \"Greatest Treasure\"",
    "61": "Jeweled Pagoda \"Radiant Treasure\"",
    "63": "Jeweled Pagoda \"Radiant Treasure Gun\"",
    "64": "Jeweled Pagoda \"Radiant Treasure Gun\"",
    "65": "Light Sign \"Absolute Justice\"",
    "67": "Light Sign \"Aura of Justice\"",
    "69": "Buddhist Art \"Most Valuable Vajra\"",
    "71": "Buddha's Light \"Vajra of Perfect Buddhism\"",
    "72": "Buddha's Light \"Vajra of Perfect Buddhism\"",
    "73": "Light Sign \"Demon of Purification\"",
    "75": "Light Sign \"Demon of Purification\"",
    "76": "\"Complete Clarification\"",
    "77": "Magic \"Omen of Purple Clouds\"",
    "79": "Good Omen \"Cloudy Way in Purple\"",
    "80": "Good Omen \"Nirvana's Cloudy Way in Purple\"",
    "81": "Magic \"Mystic Fragrance of a Makai Butterfly\"",
    "83": "Magic \"Magic Butterfly\"",
    "85": "Light Magic \"Star Maelstrom\"",
    "87": "Light Magic \"Magic Milky Way\"",
    "88": "Light Magic \"Magic Milky Way\"",
    "89": "Great Magic \"Devil's Recitation\"",
    "91": "Great Magic \"Devil's Recitation\"",
    "92": "Great Magic \"Devil's Recitation\"",
    "94": "\"Nikou Hijiri's Air Scroll\"",
    "95": "Superhuman \"Byakuren Hijiri\"",
    "96": "Flying Bowl \"Flying Fantastica\"",
    "98": "Flying Bowl \"Legendary Flying Saucer\"",
    "99": "Flying Bowl \"Legendary Flying Saucer\"",
    "100": "Umbrella Sign \"Lightly Falling Large Raindrops\"",
    "101": "Surprising Rain \"Guerrilla Typhoon\"",
    "102": "Halo \"Karakasa Surprising Flash\"",
    "103": "Ominous Clouds \"Heian Dark Clouds\"",
    "104": "Unidentified \"Red UFO Invasion of Rage\"",
    "105": "Nue Sign \"Mysterious Snake Show\"",
    "106": "Unidentified \"Blue UFO Invasion of Grief\"",
    "107": "Nue Sign \"Danmaku Chimera\"",
    "108": "Unidentified \"Green UFO Invasion of Justice\"",
    "109": "Nue Sign \"Undefined Darkness\"",
    "110": "Unidentified \"Rainbow UFO Invasion of Terror\"",
    "111": "\"Nightmare of Heiankyou\"",
    "112": "Grudge Bow \"The Bow of Genzanmi Yorimasa\"",
    "93": "\"Amagimi Hijiri's Air Scroll\""
}