{ 	"77": "Fire Sign \"Blast Burn\"",
    "78": "Fire Sign \"Blast Burn\"",
    "79": "Z-Fire \"Inferno Overdrive\"",
    "80": "Z-Fire \"Inferno Overdrive\"",
    "81": "Fire Sign \"Din's Fire\"",
    "82": "Fire Sign \"Din's Fire\"",
    "83": "God's Flame \"Wrath of Din\"",
    "84": "God's Flame \"Wrath of Din\"",
    "85": "Rainbow Sign \"Laser Lightshow\"",
    "86": "Rainbow Sign \"Laser Lightshow\"",
    "87": "Rainbow Storm \"Starlight Typhoon\"",
    "88": "Rainbow Storm \"Starlight Typhoon\"",
    "89": "Rainbow Sign \"Last Prism\"",
    "90": "Rainbow Sign \"Last Prism\"",
    "91": "Sarah's Heart \"Rainbow Prism\"",
    "92": "Sarah's Heart \"Rainbow Prism\"",
    "93": "Electric Sign \"Charge Beam\"",
    "94": "Electric Sign \"Charge Beam\"",
    "95": "Electric Blast \"Zap Cannon\"",
    "96": "Electric Blast \"Zap Cannon\"",
    "97": "Magicannon \"Final Prism\"",
    "98": "Magicannon \"Final Prism\"",
    "99": "Magicannon \"Final Last Prism\""
}