{ 	"54": "Dream Sign \"Duplex Barrier\"",
    "55": "Dream Sign \"Duplex Barrier\"",
    "56": "Dream Land \"Super Duplex Barrier\"",
    "57": "Dream Land \"Super Duplex Barrier\"",
    "58": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "59": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "60": "Scattered Spirit \"Fantasy Seal -Worn-\"",
    "61": "Scattered Spirit \"Fantasy Seal -Worn-\"",
    "62": "Dream Sign \"Evil-Sealing Circle\"",
    "63": "Dream Sign \"Evil-Sealing Circle\"",
    "64": "Divine Arts \"Omnidirectional Demon-Binding Circle\"",
    "65": "Divine Arts \"Omnidirectional Dragon-Slaying Circle\"",
    "66": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "67": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "68": "Migrating Spirit \"Fantasy Seal -Marred-\"",
    "69": "Migrating Spirit \"Fantasy Seal -Marred-\"",
    "70": "Boundary \"Duplex Danmaku Barrier\"",
    "71": "Boundary \"Duplex Danmaku Barrier\"",
    "72": "Great Barrier \"Hakurei Danmaku Barrier\"",
    "73": "Great Barrier \"Hakurei Danmaku Barrier\"",
    "74": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "75": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "76": "Divine Spirit \"Fantasy Seal -Blink-\""
}